Controllers/StudentController.cs
using System;
using System.Net;
using System.Web;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using Student_Management_System.Context;

namespace Student_Management_System.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        studentmanagementsystem_Entities1 dbObj = new studentmanagementsystem_Entities1();

        public ActionResult Student(student obj)
        {
            var classList = dbObj.classes.ToList();
            ViewBag.id = new MultiSelectList(classList, "id", "name", "section");

            return View(obj);
        }

        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                // return a bad request
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            student student = dbObj.students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        [HttpPost]
        public ActionResult AddStudent(student model)
        {
            if (ModelState.IsValid)
            {
                student std = new student();
                std.std_id = model.std_id;
                std.std_Fname = model.std_Fname;
                std.std_Lname = model.std_Lname;
                std.std_Fathername = model.std_Fathername;
                std.std_Mothername = model.std_Mothername;
                std.std_gender = model.std_gender;
                std.std_phone = model.std_phone;
                std.std_address = model.std_address;
                std.std_email = model.std_email;
                std.std_nationality = model.std_nationality;
                std.std_dob = model.std_dob;
                std.std_doa = model.std_doa;
                std.std_age = model.std_age;
                std.std_religion = model.std_religion;
                std.std_class_id = model.std_class_id;

                var classList = dbObj.classes.ToList();
                ViewBag.id = new MultiSelectList(classList, "id", "name", "section");
                if (model.std_id == 0)
                {
                    dbObj.students.Add(std);
                    dbObj.SaveChanges();
                }
                else
                {
                    dbObj.Entry(std).State = System.Data.Entity.EntityState.Modified;
                    dbObj.SaveChanges();
                }

            }
            ModelState.Clear();

            return RedirectToAction("StudentList");
        }

        public ActionResult StudentList(string searchBy, string searchValue)
        {
            List<JoinClass> jc = new List<JoinClass>();
            string constrg = @"Data Source=sql.bsite.net\MSSQL2016;Initial Catalog=studentmanagementsystem_;Persist Security Info=True;User ID=studentmanagementsystem_;Password=student123";
            SqlConnection sql = new SqlConnection(constrg);
            string sqlqu = "select student.std_id,student.std_Fname,student.std_Lname,student.std_Fathername,student.std_Mothername,student.std_gender,student.std_phone,student.std_address" +
                ", student.std_email,student.std_nationality,student.std_dob,student.std_doa,student.std_age,student.std_religion,student.std_class_id,class.name from " +
                "student inner join class on student.std_class_id=class.id";
            SqlCommand sqlComm = new SqlCommand(sqlqu, sql);
            SqlDataAdapter sda = new SqlDataAdapter(sqlComm);
            DataTable dt = new DataTable();
            sda.Fill(dt);
            foreach (DataRow dr in dt.Rows)
            {
                JoinClass jcobj = new JoinClass();
                jcobj.std_id = (int)dr["std_id"];
                jcobj.std_Fname = dr["std_Fname"].ToString();
                jcobj.std_Lname = dr["std_Lname"].ToString();
                jcobj.std_Fathername = dr["std_Fathername"].ToString();
                jcobj.std_Mothername = dr["std_Mothername"].ToString();
                jcobj.std_gender = dr["std_gender"].ToString();
                jcobj.std_phone = dr["std_phone"].ToString();
                jcobj.std_address = dr["std_address"].ToString();
                jcobj.std_email = dr["std_email"].ToString();
                jcobj.std_nationality = dr["std_nationality"].ToString();
                jcobj.std_dob = (DateTime)dr["std_dob"];
                jcobj.std_doa = (DateTime)dr["std_doa"];
                jcobj.std_age = (int)dr["std_age"];
                jcobj.std_religion = dr["std_religion"].ToString();
                jcobj.std_class_id = (int)dr["std_class_id"];
                jcobj.ClassName = dr["name"].ToString();
                jc.Add(jcobj);
            }

            if (string.IsNullOrEmpty(searchValue))
            {
                TempData["InfoMessage"] = "Please provide search value.";
                return View(jc);
            }
            else
            {
                if (searchBy.ToLower() == "std_fname")
                {
                    var searchByFname = jc.Where(p => p.std_Fname.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByFname);
                }
                else if (searchBy.ToLower() == "std_phone")
                {
                    var searchByPhone = jc.Where(p => p.std_phone.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByPhone);
                }
                else if (searchBy.ToLower() == "classname")
                {
                    var searchByClass = jc.Where(p => p.ClassName.ToLower().Contains(searchValue.ToLower()));
                    return View(searchByClass);
                }
            }

            return View(jc);
        }
    }
}

Controllers/UserController.cs
using Student_Management_System.Context;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

namespace Student_Management_System.Controllers
{
    public class UserController : Controller
    {
        studentmanagementsystem_Entities1 dbObj = new studentmanagementsystem_Entities1();
        // GET: User
        [Authorize]
        public ActionResult Index()
        {
            if (Session["UserName"] != null)
                return View("UserDashBoard");
            return View();
        }

        [AllowAnonymous]
        public ActionResult Signup()
        {
            tbl_account Account = new tbl_account();
            return View(Account);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Signup(tbl_account model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.msg = "Please enter the details to Sign Up!";
                model = null;
                return View("Signup");
            }
            else
            {
                if (model != null)
                {
                    dbObj.tbl_account.Add(model);                         // Adding the data into tbl_account table 
                    dbObj.SaveChanges();
                    ViewBag.msg = "Account created successfully!";
                    model = null;
                    return View("Login");
                }
                else
                {
                    ViewBag.msg = "Please enter the details to Sign Up!";
                    model = null;
                    return View("Signup");
                }
            }
        }

        [AllowAnonymous]
        public ActionResult Login()
        {
            tbl_account Account = new tbl_account();
            if (Session["UserName"] != null)
                return View("UserDashBoard");
            return View(Account);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(tbl_account model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.msg = "Please enter the details to Login!";
                model = null;
                return View();
            }
            else
            {
                if (model != null)
                {
                    tbl_account s = dbObj.tbl_account.Where(a => a.email.Equals(model.email) && a.password.Equals(model.password)).SingleOrDefault();
                    if (s != null)
                    {
                        Session["UserID"] = s.userid.ToString();
                        Session["UserName"] = s.name.ToString();
                        FormsAuthentication.SetAuthCookie(model.email, false);
                        return Redirect("UserDashBoard");
                    }
                    else
                    {
                        ViewBag.msg = "Invalid Email or Password!";
                        model = null;
                    }
                    return View();
                }
                else
                {
                    ViewBag.msg = "Please enter the details to Login!";
                    model = null;
                    return View("Login");
                }
            }
        }

        [Authorize]
        public ActionResult UserDashBoard()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            FormsAuthentication.SignOut();
            return View("Login");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

@{
    Layout = null;
}

<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SMS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap-chosen.css" rel="stylesheet" />
    <style>
        @@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: "Poppins", sans-serif;
        }

        body {
            padding: 0px !important;
        }

        .container-fluid {
            padding-right: 15px !important;
            padding-left: 15px !important;
        }

        .sidebar {
            position: fixed;
            left: 0;
            top: 0;
            height: 100%;
            width: 78px;
            background: #11101D;
            padding: 6px 14px;
            z-index: 99;
            transition: all 0.5s ease;
        }

            .sidebar.open {
                width: 250px;
            }

            .sidebar .logo-details {
                height: 60px;
                display: flex;
                align-items: center;
                position: relative;
            }

                .sidebar .logo-details .icon {
                    opacity: 0;
                    transition: all 0.5s ease;
                }

                .sidebar .logo-details .logo_name {
                    color: #fff;
                    font-size: 16px;
                    font-weight: 600;
                    opacity: 0;
                    transition: all 0.5s ease;
                }

            .sidebar.open .logo-details .icon,
            .sidebar.open .logo-details .logo_name {
                opacity: 1;
            }

            .sidebar .logo-details #btn {
                position: absolute;
                top: 50%;
                right: 0;
                transform: translateY(-50%);
                font-size: 22px;
                transition: all 0.4s ease;
                font-size: 23px;
                text-align: center;
                cursor: pointer;
                transition: all 0.5s ease;
            }

            .sidebar.open .logo-details #btn {
                text-align: right;
            }

            .sidebar i {
                color: #fff;
                height: 60px;
                min-width: 50px;
                font-size: 28px;
                text-align: center;
                line-height: 60px;
            }

            .sidebar .nav-list {
                margin-top: 20px;
                height: 100%;
            }

            .sidebar li {
                position: relative;
                margin: 8px 0;
                list-style: none;
            }

                .sidebar li .tooltip {
                    position: absolute;
                    top: -20px;
                    left: calc(100% + 15px);
                    z-index: 3;
                    background: #fff;
                    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
                    padding: 6px 12px;
                    border-radius: 4px;
                    font-size: 15px;
                    font-weight: 400;
                    opacity: 0;
                    white-space: nowrap;
                    pointer-events: none;
                    transition: 0s;
                }

                .sidebar li:hover .tooltip {
                    opacity: 1;
                    pointer-events: auto;
                    transition: all 0.4s ease;
                    top: 50%;
                    transform: translateY(-50%);
                }

            .sidebar.open li .tooltip {
                display: none;
            }

            .sidebar input {
                font-size: 15px;
                color: #FFF;
                font-weight: 400;
                outline: none;
                height: 50px;
                width: 100%;
                width: 50px;
                border: none;
                border-radius: 12px;
                transition: all 0.5s ease;
                background: #1d1b31;
            }

            .sidebar.open input {
                padding: 0 20px 0 50px;
                width: 100%;
            }

            .sidebar .bx-search {
                position: absolute;
                top: 50%;
                left: 0;
                transform: translateY(-50%);
                font-size: 22px;
                background: #1d1b31;
                color: #FFF;
            }

            .sidebar.open .bx-search:hover {
                background: #1d1b31;
                color: #FFF;
            }

            .sidebar .bx-search:hover {
                background: #FFF;
                color: #11101d;
            }

            .sidebar li a {
                display: flex;
                height: 100%;
                width: 100%;
                border-radius: 12px;
                align-items: center;
                text-decoration: none;
                transition: all 0.4s ease;
                background: #11101D;
            }

                .sidebar li a:hover {
                    background: #FFF;
                }

                .sidebar li a .links_name {
                    color: #fff;
                    font-size: 15px;
                    font-weight: 400;
                    white-space: nowrap;
                    opacity: 0;
                    pointer-events: none;
                    transition: 0.4s;
                }

            .sidebar.open li a .links_name {
                opacity: 1;
                pointer-events: auto;
            }

            .sidebar li a:hover .links_name,
            .sidebar li a:hover i {
                transition: all 0.5s ease;
                color: #11101D;
            }

            .sidebar li i {
                height: 50px;
                line-height: 50px;
                font-size: 18px;
                border-radius: 12px;
            }

            .sidebar li.profile {
                position: fixed;
                height: 60px;
                width: 78px;
                left: 0;
                bottom: -8px;
                padding: 10px 14px;
                background: #1d1b31;
                transition: all 0.5s ease;
                overflow: hidden;
            }

            .sidebar.open li.profile {
                width: 250px;
            }

            .sidebar li .profile-details {
                display: flex;
                align-items: center;
                flex-wrap: nowrap;
            }

            .sidebar li img {
                height: 45px;
                width: 45px;
                object-fit: cover;
                border-radius: 6px;
                margin-right: 10px;
            }

            .sidebar li.profile .name,
            .sidebar li.profile .job {
                font-size: 15px;
                font-weight: 400;
                color: #fff;
                white-space: nowrap;
            }

            .sidebar li.profile .job {
                font-size: 12px;
            }

            .sidebar .profile #log_out {
                position: absolute;
                top: 50%;
                right: 0;
                transform: translateY(-50%);
                background: #1d1b31;
                width: 100%;
                height: 60px;
                line-height: 60px;
                border-radius: 0px;
                transition: all 0.5s ease;
            }

            .sidebar.open .profile #log_out {
                width: 50px;
                background: none;
            }

        .home-section {
            background: #E4E9F7;
            min-height: 100vh;
            position: relative;
            top: 0;
            left: 78px;
            width: calc(100% - 78px);
            transition: all 0.5s ease;
            z-index: 2;
        }

        .sidebar.open ~ .home-section {
            left: 250px;
            width: calc(100% - 250px);
        }

        .home-section .text {
            display: inline-block;
            color: #11101d;
            font-size: 25px;
            font-weight: 500;
            margin: 18px
        }

        @@media (max-width: 420px) {
            .sidebar li .tooltip {
                display: none;
            }
        }

        table {
            width: -webkit-fill-available !important;
        }

        .tdata {
            padding: 5px !important;
            border: 2px black solid !important;
            text-align: center !important;
            color: black !important;
        }

        .form-horizontal .form-group {
            margin: 0px !important;
            margin-bottom: 15px !important;
        }
    </style>
</head>
<body>
    <div class="sidebar">
        <div class="logo-details">
            <i class='bx bxl-c-plus-plus icon'></i>
            <div class="logo_name">Student Management</div>
            <i class='bx bx-menu' id="btn"></i>
        </div>
        <ul class="nav-list">
            @*<li>
                    <i class='bx bx-search'></i>
                    <input type="text" placeholder="Search...">
                    <span class="tooltip">Search</span>
                </li>*@
            <li>
                <a href="@Url.Action("UserDashBoard","User")">
                    <i class='bx bx-grid-alt'></i>
                    <span class="links_name">Dashboard</span>
                </a>
                <span class="tooltip">Dashboard</span>
            </li>
            <li>
                <a href="@Url.Action("StudentList","Student")">
                    <i class='bx bx-user'></i>
                    <span class="links_name">Manage Student</span>
                </a>
                <span class="tooltip">Manage Student</span>
            </li>
            <li>
                <a href="@Url.Action("ClassList","Class")">
                    <i class='bx bx-heart'></i>
                    <span class="links_name">Manage Class</span>
                </a>
                <span class="tooltip">Manage Class</span>
            </li>
            <li>
                <a href="@Url.Action("TimeTableList","ClassRoutine")">
                    <i class='bx bx-pie-chart-alt-2'></i>
                    <span class="links_name">Manage Time Table</span>
                </a>
                <span class="tooltip">Manage Time Table</span>
            </li>
            <li>
                <a href="@Url.Action("FeeList","Fees")">
                    <i class='bx bx-folder'></i>
                    <span class="links_name">Manage Fees</span>
                </a>
                <span class="tooltip">Manage Fees</span>
            </li>
            <li>
                <a href="@Url.Action("ResultList","Result")">
                    <i class='bx bx-cog'></i>
                    <span class="links_name">Manage Result</span>
                </a>
                <span class="tooltip">Manage Result</span>
            </li>
            <li class="profile">
                <div class="profile-details">
                    <div class="name_job">
                        <div class="name">Dev Ahsan</div>
                        <div class="job">Web designer</div>
                    </div>
                </div>
                <a href="@Url.Action("Logout","User")">
                    <i class='bx bx-log-out' id="log_out" style="color:white !important;"></i>
                </a>
            </li>
        </ul>
    </div>
    <section class="home-section">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </section>
    <script>
        let sidebar = document.querySelector(".sidebar");
        let closeBtn = document.querySelector("#btn");
        let searchBtn = document.querySelector(".bx-search");

        closeBtn.addEventListener("click", () => {
            sidebar.classList.toggle("open");
            menuBtnChange();
        });

        searchBtn.addEventListener("click", () => {
            sidebar.classList.toggle("open");
            menuBtnChange();
        });


        function menuBtnChange() {
            if (sidebar.classList.contains("open")) {
                closeBtn.classList.replace("bx-menu", "bx-menu-alt-right");
            } else {
                closeBtn.classList.replace("bx-menu-alt-right", "bx-menu");
            }
        }
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/chosen.jquery.js"></script>
</body>
</html>